name: Build APK

# هذا الجزء يعني أن التطبيق سيتم بناؤه تلقائياً كلما أضفت كوداً جديداً
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تثبيت لغة جافا (ضرورية للأندرويد)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. تثبيت محرك فلاتر (Flutter)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # لتسريع البناء في المرات القادمة

      # 4. تحميل المكتبات اللازمة للتطبيق
      - name: Install dependencies
        run: flutter pub get

      # 5. طبخ الكود وتحويله إلى ملف APK احترافي
      - name: Build APK
        run: flutter build apk --release

      # 6. رفع الملف النهائي لتستطيع تحميله على هاتفك
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: C-Master-Pro-Release
          path: build/app/outputs/flutter-apk/app-release.apk
